ALTER TABLE IF EXISTS AGENDAMENTO
DROP CONSTRAINT IF EXISTS FKGUHEPAX6V6KX4V8A8B4QTYH16;

ALTER TABLE IF EXISTS AGENDAMENTO
DROP CONSTRAINT IF EXISTS FK_AGENDAMENTO_STATUS;

DROP TABLE IF EXISTS AGENDAMENTO_STATUS;

CREATE TABLE AGENDAMENTO_STATUS (
	ID INT NOT NULL PRIMARY KEY,
	DESCRICAO VARCHAR(100) NOT NULL
);