DROP TABLE IF EXISTS CONTA;
DROP TABLE IF EXISTS USUARIO;

CREATE TABLE CONTA (
	ID VARCHAR(10) NOT NULL PRIMARY KEY,
	NOME_PROPRIETARIO VARCHAR(50) NOT NULL,
	SALDO NUMERIC(19,2) NOT NULL,
	SENHA VARCHAR(255) NOT NULL
);